/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <iostream>
#include <opencv2/opencv.hpp>

using namespace cv;
using namespace std;

/* Header for class es_hicsuntleon_collen_ndkopencvtest1_OpenCVNativeClass */

#ifndef _Included_es_hicsuntleon_collen_ndkopencvtest1_OpenCVNativeClass
#define _Included_es_hicsuntleon_collen_ndkopencvtest1_OpenCVNativeClass
#ifdef __cplusplus
extern "C" {
#endif

int toGray(Mat img, Mat &gray);

/*
 * Class:     es_hicsuntleon_collen_ndkopencvtest1_OpenCVNativeClass
 * Method:    convertGray
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_es_hicsuntleon_collen_ndkopencvtest1_OpenCVNativeClass_convertGray
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
